/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ApiPortalSplatRouteImport } from './routes/api/portal/$'
import { Route as ApiPublicHooksMaintenanceRouteImport } from './routes/api/public/hooks/maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSplatRoute = ApiPortalSplatRouteImport.update({
  id: '/api/portal/$',
  path: '/api/portal/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMaintenanceRoute =
  ApiPublicHooksMaintenanceRouteImport.update({
    id: '/api/public/hooks/maintenance',
    path: '/api/public/hooks/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/api/portal/$': typeof ApiPortalSplatRoute
  '/api/public/hooks/maintenance': typeof ApiPublicHooksMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/api/portal/$': typeof ApiPortalSplatRoute
  '/api/public/hooks/maintenance': typeof ApiPublicHooksMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/api/portal/$': typeof ApiPortalSplatRoute
  '/api/public/hooks/maintenance': typeof ApiPublicHooksMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/track'
    | '/api/portal/$'
    | '/api/public/hooks/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/track'
    | '/api/portal/$'
    | '/api/public/hooks/maintenance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/track'
    | '/api/portal/$'
    | '/api/public/hooks/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TrackRoute: typeof TrackRoute
  ApiPortalSplatRoute: typeof ApiPortalSplatRoute
  ApiPublicHooksMaintenanceRoute: typeof ApiPublicHooksMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/$': {
      id: '/api/portal/$'
      path: '/api/portal/$'
      fullPath: '/api/portal/$'
      preLoaderRoute: typeof ApiPortalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/maintenance': {
      id: '/api/public/hooks/maintenance'
      path: '/api/public/hooks/maintenance'
      fullPath: '/api/public/hooks/maintenance'
      preLoaderRoute: typeof ApiPublicHooksMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRoute,
  ApiPortalSplatRoute: ApiPortalSplatRoute,
  ApiPublicHooksMaintenanceRoute: ApiPublicHooksMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
